# Generated by Django 4.1.3 on 2022-11-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='correo',
        ),
        migrations.AddField(
            model_name='empleados',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='empleados',
            name='membresia',
            field=models.BooleanField(null=True, verbose_name=''),
        ),
    ]
