# Generated by Django 4.1.3 on 2022-11-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_Blog', '0003_remove_jefes_correo_jefes_email_jefes_membresia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='sueldo',
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name=''),
        ),
    ]
