# Generated by Django 4.1.3 on 2022-11-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_Blog', '0004_remove_clientes_sueldo_clientes_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='membresia',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='membresia',
        ),
        migrations.RemoveField(
            model_name='jefes',
            name='membresia',
        ),
    ]
