# Generated by Django 4.1.3 on 2022-11-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_Blog', '0005_remove_clientes_membresia_remove_empleados_membresia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
        migrations.RenameModel(
            old_name='Jefes',
            new_name='Jefe',
        ),
    ]
